server:
  port: 8080

spring:
  application:
    name: control-system
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: squd
        use_sql_comments: true
        format_sql: true
        criteria:
          literal_handling_mode: BIND
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sklbx?currentSchema=squd
    username: postgres
    password: 1234
