server:
  port: 8082

logging:
  level:
    org.springframework: INFO
    ru.unit_techno.car_entry_control: DEBUG

ws:
  topics:
    not_active: "/topic/newrfidlabel"

spring:
  application:
    name: car-entry-control
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: car_entry_control
        use_sql_comments: true
        format_sql: true
        criteria:
          literal_handling_mode: BIND
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/unit_techno?currentSchema=car_entry_control
    username: car_entry_admin
    password: squd

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

user-model.mail.host: smtp.yandex.ru
user-model.mail.username: crime-it-tech-user@yandex.ru
user-model.mail.password: jrRJnutB0t
user-model.mail.port: 465
user-model.mail.protocol: smtps
user-model.debug: false

event:
  type:
    1239:
      info: "административный корпус"
      entryType: OUT
    2345:
      info: "задний проход"
      entryType: IN